version: 2.1

jobs:
  tryport:
    machine:
      image: ubuntu-1604:202004-01
    steps:
    
      - run:
          name: Install Node & NPM
          command: |
            sudo apt-get install nodejs
            sudo apt-get install npm
      - run:
          name: NPM port scramble
          command: |
            npm stop
            npm -- --port 38129

 
workflows:
  welcome:
    jobs:
      - tryport
