version: 2.1

commands:
  promote:
    parameters:
      fail-if-semver-not-indicated:
        description: |
            Whether to fail if the commit subject did not include [semver:patch|minor|major|skip]
        type: boolean
        
    steps:
      - run:
          environment:
            SHOULD_FAIL: <<parameters.fail-if-semver-not-indicated>>
          command: |
            CheckIncrement() {
                          echo "$SHOULD_FAIL"
                          echo "${SHOULD_FAIL}"
            }
            
            CheckIncrement

jobs:
  trymote:
    docker:
      - image: circleci/python
    steps:
      - promote:
          fail-if-semver-not-indicated: true
    
 
workflows:
  welcome:
    jobs:
      - trymote
