version: 2.1

jobs:
  tryport:
    machine:
      image: ubuntu-1604:202004-01
    steps:
    
      - run:
          name: Install Node & NPM
          command: |
            sudo apt-get update && sudo apt-get install nodejs
            sudo apt-get update && sudo apt-get install npm
      - run:
          name: NPM port scramble
          command: |
            npm start -- --port 38129
          when: always
            
      - run:
          name: Nose port scramble
          command: |
            node server.js 38135
          when: always
            


 
workflows:
  welcome:
    jobs:
      - tryport
