version: 2.1

jobs:
  lenew:
    docker:
      - image: postman/newman:4.4.1

    steps:
      - run: echo "Hello"
      - run :
          name: Run check 1
          command: echo "Run check 1"
      - run :
          name: Run check 2
          command: echo "Run check 1"

 
workflows:
  welcome:
    jobs:
      - lenew
