version: 2.1

commands:
  promote:
    parameters:
      fail-if-semver-not-indicated:
        description: |
            Whether to fail if the commit subject did not include [semver:patch|minor|major|skip]
        type: boolean
        
    steps:
      - run:
          environment:
            SHOULD_FAIL: <<parameters.fail-if-semver-not-indicated>>
          command: |
            CheckIncrement() {
                          if [ "$SHOULD_FAIL" == "1" ] ;then
                            echo "Hello"
                          fi
                          
                          if [ "${SHOULD_FAIL}" == "0" ]; then
                            echo "Hiya"
                          fi
            }
            
            CheckIncrement

jobs:
  trymote:
    docker:
      - image: circleci/python
    steps:
      - promote:
          fail-if-semver-not-indicated: true
    
 
workflows:
  welcome:
    jobs:
      - trymote
