version: 2.1

jobs:
  trymote:
    docker:
      - image: circleci/python

    steps:
      - run:
          shell: /bin/bash +eo pipefail
          command: |
            ls /toto; echo 'export EXIT_1=$?' >> $BASH_ENV
            true
      - run:
          command: echo "This ran"
#           when: always
      - run: |
          if [ $EXIT_1 != 0 ]; then
            echo "ls failed"
          fi
    
 
workflows:
  welcome:
    jobs:
      - trymote
