version: 2

jobs:
  try:
    parameters: 
      condition:
        type: string
        default: blaaaaaaaah
        
    docker:
      - image: circleci/python
    steps:
      - run: echo "Hello there"
      - run: echo $lacond
      
workflows:
  build:
    jobs:
      - build
