version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-1604:202004-01
    steps:
      - run:
          name: NPM port scramble
          command: |
            sudo npm stop
            sudo npm -- --port 38129

 
workflows:
  welcome:
    jobs:
      - trymote
