version: 2

jobs:
  build:
    parameters: 
      condition:
        type: string
        default: blaaaaaaaah
        
    docker:
      - image: circleci/python
    steps:
      - run: echo "Hello there"
      - run: echo << parameters.condition >>
      
workflows:
  version: 2
  build:
    jobs:
      - build
