version: 2.1

jobs:
  trymote:
    docker:
      - image: circleci/python
    shell: set +eo pipefail
    steps:
      - run: |
          ls /toto
      - run:
          command: echo "This ran"
          when: always
    
 
workflows:
  welcome:
    jobs:
      - trymote
