version: 2.1

setup: true

parameters:
  condition:
    type: string
    default: ''
                
orbs:
  continuation: circleci/continuation@0.1.2

jobs:
  paameters:
    lacondition:
      type: env_var_nme
      default: condition_needed
      
  setup:
    executor: continuation/default
    steps:
      - checkout
      - run: echo ${<< parameters.lacondition >>}
      - run:
          name: Generate config
          command: |
            cat > main.yml \<<- "EOF"
            version: 2.1
            parameters:
              condition:
                type: string
                default: ''
            jobs:
              job1:
                docker:
                  - image: cimg/base:2021.04
                steps:
                  - run: echo dynamic config!
                  - run: echo << pipeline.parameters.condition >>
            workflows:
             workflow1:
              jobs:
               - job1
            EOF
      - continuation/continue:
          configuration_path: main.yml
          parameters: '{"condition":"${<< parameters.lacondition >>}"}'

workflows:
  setup:
    jobs:
      - setup
