version: 2.1

parameters: 
  condition:
    type: string
    default: $condition_needed

jobs:
  trymote:
    docker:
      - image: circleci/python
    steps:
      - run: echo "Hello there"
      - run: echo << pipeline.parameters.condition >>
      
      
    
 
workflows:
  welcome:
    jobs:
      - trymote
