version: 2.1

jobs:
  trymote:
    docker:
      - image: circleci/python

    steps:
      - run:
          shell: /bin/bash
          command: ls /toto
      - run:
          command: echo "This ran"
          when: always
    
 
workflows:
  welcome:
    jobs:
      - trymote
