version: 2.1

jobs:
  trymote:
    docker:
      - image: circleci/python
    shell: /bin/bash +e

    steps:
      - run:
          command: |
            ls /toto
            circleci-agent step halt
      - run:
          command: echo "This ran"
          when: always

 
workflows:
  welcome:
    jobs:
      - trymote
