version: 2.1

jobs:
  trymote:
    docker:
      - image: circleci/python
    steps:
      - run: |
          set +e
          ls /toto
          echo "Same step as failing command"
      - run: echo "This ran"
          when: always
    
 
workflows:
  welcome:
    jobs:
      - trymote
