version: 2.1

jobs:
  try:
    parameters: 
      condition:
        type: string
        default: blaaaaaaaah
        
    docker:
      - image: circleci/python
    steps:
      - run: echo "Hello there"
      - run: echo << parameters.condition >>
      - run: echo $FOO
      
workflows:
  build:
    jobs:
      - try
