version: 2.1

jobs:
  try:
    parameters: 
      condition:
        type: env_var_name
        default: FOO
        
    docker:
      - image: circleci/python
    steps:
      - run: echo "Hello there"
      - run: echo ${<< parameters.condition >>}
      - run: echo $FOO
      
workflows:
  build:
    jobs:
      - try:
          pre-steps:
            - run: |
                if [[ $FOO = "tototiti" ]]; then
                 echo "Hello"
                fi
