version: 2.1

jobs:
  trymote:
    docker:
      - image: circleci/python
    steps:
      - run: |
          set +e
          ls /toto
      - run: echo "This ran"
    
 
workflows:
  welcome:
    jobs:
      - trymote
